?start: exp

?exp: exp "+" exp1             -> plus
      | exp "-" exp1          -> minus
      | exp1

?exp1: "\\" NAME "." exp             -> lam
      | exp2   
?exp2: exp2 exp3                    -> app
      | exp3
?exp3: NAME                         -> var
      | NUMBER                      -> number
      | "(" exp ")"   
    

NAME: /[a-z_][a-zA-Z0-9_]*/
NUMBER: /\d+(\.\d+)?/    


%import common.WS
%ignore WS

%ignore /\/\/[^\n]*/  
%ignore /\/\*[\s\S]*?\*\//  
